<?php

namespace Container8HogeTI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O64cWSRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O64cWSR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O64cWSR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'job' => ['privates', '.errored..service_locator.O64cWSR.App\\Entity\\Job', NULL, 'Cannot autowire service ".service_locator.O64cWSR": it references class "App\\Entity\\Job" but no such service exists.'],
        ], [
            'job' => 'App\\Entity\\Job',
        ]);
    }
}
