<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOl2pvUm\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOl2pvUm/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOl2pvUm.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOl2pvUm\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOl2pvUm\App_KernelProdContainer([
    'container.build_hash' => 'Ol2pvUm',
    'container.build_id' => 'e9f58fbc',
    'container.build_time' => 1606750128,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOl2pvUm');
