<?php

namespace ContainerOl2pvUm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\JobController::delete' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'App\\Controller\\JobController::edit' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'App\\Controller\\JobController::index' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\JobController::show' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\JobController:delete' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'App\\Controller\\JobController:edit' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'App\\Controller\\JobController:index' => ['privates', '.service_locator.UBsX6gB', 'get_ServiceLocator_UBsX6gBService', true],
            'App\\Controller\\JobController:show' => ['privates', '.service_locator.O64cWSR', 'get_ServiceLocator_O64cWSRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\JobController::delete' => '?',
            'App\\Controller\\JobController::edit' => '?',
            'App\\Controller\\JobController::index' => '?',
            'App\\Controller\\JobController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\JobController:delete' => '?',
            'App\\Controller\\JobController:edit' => '?',
            'App\\Controller\\JobController:index' => '?',
            'App\\Controller\\JobController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
