<?php

namespace ContainerOl2pvUm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\JobRepository' shared autowired service.
     *
     * @return \App\Repository\JobRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\JobRepository'] = new \App\Repository\JobRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
