<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMPK3A3R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMPK3A3R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMPK3A3R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMPK3A3R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMPK3A3R\App_KernelDevDebugContainer([
    'container.build_hash' => 'MPK3A3R',
    'container.build_id' => '5a634e2e',
    'container.build_time' => 1606849136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMPK3A3R');
