<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUuhD14X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUuhD14X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUuhD14X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUuhD14X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUuhD14X\App_KernelDevDebugContainer([
    'container.build_hash' => 'UuhD14X',
    'container.build_id' => 'c293dce4',
    'container.build_time' => 1601553604,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUuhD14X');
