<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Job extends \App\Entity\Job implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'jobtitle', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'companytitle', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'dateapplication', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'contact', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'url', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'feedback'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'jobtitle', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'companytitle', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'dateapplication', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'contact', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'url', '' . "\0" . 'App\\Entity\\Job' . "\0" . 'feedback'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Job $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getJobtitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobtitle', []);

        return parent::getJobtitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setJobtitle(string $jobtitle): \App\Entity\Job
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJobtitle', [$jobtitle]);

        return parent::setJobtitle($jobtitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanytitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanytitle', []);

        return parent::getCompanytitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompanytitle(?string $companytitle): \App\Entity\Job
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompanytitle', [$companytitle]);

        return parent::setCompanytitle($companytitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateapplication(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateapplication', []);

        return parent::getDateapplication();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateapplication(\DateTimeInterface $dateapplication): \App\Entity\Job
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateapplication', [$dateapplication]);

        return parent::setDateapplication($dateapplication);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', []);

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact(?string $contact): \App\Entity\Job
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', [$contact]);

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', []);

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl(?string $url): \App\Entity\Job
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', [$url]);

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeedback(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeedback', []);

        return parent::getFeedback();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeedback(?string $feedback): \App\Entity\Job
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeedback', [$feedback]);

        return parent::setFeedback($feedback);
    }

}
